In [221]:
import re
import pickle
import pandas as pd
import numpy as np
from numpy import nan

In [222]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [223]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,average_precision_score,recall_score
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection, naive_bayes, svm
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
from sklearn.linear_model import SGDClassifier
import matplotlib.pyplot as plt

In [224]:
import pandas as pd
df= pd.read_csv('Dataset_2738_after_webscraping.csv')  

In [225]:


C = (df['Content']).tolist()

L = (df['Label']).tolist()

In [226]:
#PREPROCESSING
def preprocess(col):
    col_l = []
    for r in col:
        #print(r)
        try:
            a = r.lower() 
            a = a.replace("'s", "")
            #a = a.replace(["\n"], "hjfgjh")
            a = re.sub('[^a-zA-Z0-9 \n\.]', '',a)
            a = re.sub('[:.\n\t]', '',a)
            a = re.sub('[?:!.+,]]][]]//;]', '',a) 
            
            col_l.append(a)
        except:
            #print("No header found")
            col_l.append("No Header")
            pass

    # Downloading punkt and wordnet from NLTK
    nltk.download('punkt')
    print("------------------------------------------------------------")
    nltk.download('wordnet')
    
    wordnet_lemmatizer = WordNetLemmatizer()
    
    nltk.download('stopwords')
    
    lemmatized_text_list = []

    for s in col_l:
        #print(s)
        # Create an empty list containing lemmatized words
        lemmatized_list = []

        # Save the text and its words into an object
        #text = df.loc[row]['Content_Parsed_4']
        text_words = s.split(" ")

        # Iterate through every word to lemmatize
        for word in text_words:
            lemmatized_list.append(wordnet_lemmatizer.lemmatize(word, pos="v"))

        # Join the list
        lemmatized_text = " ".join(lemmatized_list)

        # Append to the list containing the texts
        lemmatized_text_list.append(lemmatized_text)
    
    new_lemmatized_text_list = []
    for x in lemmatized_text_list:
        new_lemmatized_text_list.append(" ".join(x.split())) 
    
    pl = pd.Series(new_lemmatized_text_list)
   # pl = pd.Series(col_l)
    stop_words = list(stopwords.words('english'))
    
    for stop_word in stop_words:
        regex_stopword = r"\b" + stop_word + r"\b"
        #pl = pd.Series(col_l)
   
        pl = pl.str.replace(regex_stopword, '')
        
    
    return pl.tolist()

In [227]:
con = preprocess(C)
#print(con)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


------------------------------------------------------------


In [228]:
len(con)

2738

In [229]:
L

['iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-pr

In [230]:
label = []

In [231]:
for i in L:
    if i == 'iot-project' or i == 'Iot-Project':
        label.append(1)
        
    elif i == 'non-iot-project':
        label.append(0)

In [232]:
len(label)

2738

In [233]:
category_codes = {'non-iot-project': 0, 'iot-project': 1,}

In [234]:
category_codes

{'non-iot-project': 0, 'iot-project': 1}

In [235]:
la2 = pd.Series(label)

In [236]:
la_2 = la2.replace({'Category_Code':category_codes})

In [237]:
la_2

0       1
1       1
2       1
3       1
4       1
       ..
2733    0
2734    0
2735    0
2736    0
2737    0
Length: 2738, dtype: int64

In [238]:
len(la_2)

2738

In [239]:
 df = pd.DataFrame({"Content":con})

In [240]:
df

Content
0     add  follow snippet   html connect  modbus ene...
1     add  follow snippet   html remote control  las...
2     add  follow snippet   html know   go check   t...
3     add  follow snippet   html  simple tutorial  c...
4     add  follow snippet   html tire  joystick cont...
...                                                 ...
2733  321 5 1 feature traditional saffron buns lusse...
2734  7358 55 18 feature  camera bag   useful  carry...
2735  5937 28 13 feature  various reason  wont bore ...
2736  2233 74 6 feature ahoy mateys fancy  cold drin...
2737  2355 44 9 feature one   many fashion trend   l...

[2738 rows x 1 columns]

In [241]:
#####################################  Training Module Starts  #########################################

In [242]:
X_train, X_test, y_train, y_test = train_test_split(df, la_2, test_size=0.15, random_state=8)

In [243]:

X_test

Content
1923  2163 78 1 feature  meat loaf   good choice    ...
1117  add  follow snippet   html   thingsio ai platf...
2154  2742 15 4 feature  make  dress  ive want    cu...
481   add  follow snippet   html use  dark sky api  ...
615   add  follow snippet   html connect multiple da...
...                                                 ...
179   add  follow snippet   html name   box  light  ...
652   add  follow snippet   html transform  energy  ...
2390  230 1 feature make  cardboard carousel  nine l...
2064  936 8 feature im  big guy   want  make  even b...
2683  14426 52 5 feature  test tube vase  exactly   ...

[411 rows x 1 columns]

In [244]:
y_train

392     1
2360    0
1589    0
2492    0
184     1
       ..
2181    0
2409    0
2033    0
1364    1
451     1
Length: 2327, dtype: int64

In [245]:
ngram_range = (1,2)
min_df = 10
max_df = 1.
max_features =300# not clear how to choose this value

In [246]:
tfidf = TfidfVectorizer(encoding='utf-8',
                        ngram_range=ngram_range,
                        stop_words=None,
                        lowercase=False,
                        max_df=max_df,
                        min_df=min_df,
                        max_features=max_features,
                        norm='l2',
                        sublinear_tf=True)

In [247]:
features_train = tfidf.fit_transform(X_train['Content']).toarray()
print(features_train)




[[0.         0.         0.         ... 0.         0.16917262 0.        ]
 [0.         0.         0.05022019 ... 0.         0.         0.        ]
 [0.         0.1856895  0.07417406 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.23613663 0.14122649 0.1423042 ]
 [0.114721   0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [248]:
features_test = tfidf.fit_transform(X_test['Content']).toarray()
print(features_test)


[[0.         0.         0.         ... 0.13206786 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.07204241 0.         ... 0.         0.0783875  0.        ]
 ...
 [0.18709476 0.         0.         ... 0.         0.         0.10855486]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.05115653 0.         0.         ... 0.         0.06094464 0.        ]]


In [249]:


#####################################  Training Module Ends  #########################################

In [250]:
################################## DECISION TREE ###############################################

In [251]:
#DTC =DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,max_features=None, max_leaf_nodes=10, min_samples_leaf=5,min_samples_split=2, min_weight_fraction_leaf=0.0,random_state=None, splitter='random')
DTC = DecisionTreeClassifier(random_state=8)
DTC.fit(features_train, y_train)
#labels_train = y_train
DTC_pred = DTC.predict(features_test)


In [252]:
print("Decision Tree Training Accuracy Score  ->",accuracy_score(y_train, DTC.predict(features_train))*100)
print("Decision Tree Testing Accuracy Score  ->",accuracy_score(y_test, DTC.predict(features_test))*100)


Decision Tree Training Accuracy Score  -> 100.0
Decision Tree Testing Accuracy Score  -> 99.51338199513383


In [253]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, DTC_pred)
print(matrix)


[[202   0]
 [  2 207]]


In [254]:
report = classification_report(y_test, DTC_pred)
print(report)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       202
           1       1.00      0.99      1.00       209

    accuracy                           1.00       411
   macro avg       1.00      1.00      1.00       411
weighted avg       1.00      1.00      1.00       411



In [255]:
##########below part is for checking the prediction using different data set########

In [256]:
dfnew= pd.read_csv('dataset75iotnoniot.csv')##75  iotnoniot projects for prediction  
#dfnew= pd.read_csv('dataset75iot.csv')#75  iot projects for prediction 
#dfnew= pd.read_csv('dataset75noniot.csv')#75  noniot projects for prediction 

In [257]:
cnew=(dfnew['descr']).tolist()
#print(cnew)

In [258]:
connew=preprocess(cnew)
print(connew)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


------------------------------------------------------------
['384 6 feature  favourite memory  fourth grade   day   class go   nature reserve  conservationists tell   grab  birdseed  hold    front      sudden  bird land   hand  proceed  eat    seed    surprise    point   life   never   close   bird  look    close theyre  exotic  interest animals   quickly   come   go    hook sadly every year bird  ingest  plastic   humans deposit   habitats  bird regularly confuse  plastics  food  eat   also fee  plastic   chicks  project aim  help   bird  little rather  allow plastics  find   landfills   go  make  recycle plastic bird feeder  design  great  people without  lot  tool andor skills   also  great homeschool project  kid   kid enjoy feed  bird    learn     end   also  great way    learn  environmental stewardship let get start teachers   use  instructable   classroom add  teacher note  share   incorporate    lesson   project   need   step    need  smaller drill bite drill four  five hole 

In [259]:
df1 = pd.DataFrame({"descr":connew})
df1

descr
0   384 6 feature  favourite memory  fourth grade ...
1   362 9 2 feature   upcycle  coffee    chic bird...
2   11300 114 24 feature build   wificameraenabled...
3   1117 6 2 feature build  birdhouse    difficult...
4   13080 39 5 feature  local woodworking club   a...
..                                                ...
70  add  follow snippet   html sony spresense boar...
71  add  follow snippet   html use  arduino  creat...
72  add  follow snippet   html 8000 rpm motor   gu...
73  add  follow snippet   html  tutorial  show   i...
74  add  follow snippet   html  micocontrollers la...

[75 rows x 1 columns]

In [260]:
#xx = pd.DataFrame({'Content':['"623. 7. 4. Featured. You can make this recipe in a 10-inch springform pan. However, I like to make this coffee cake into smaller servings. I usually split the recipe in half since I’m only cooking for two. I use three 4-inch springform pans to bake the coffee cake and spread them out between a couple days. The coffee cakes can be stored in an airtight container at room temperature for up to 2 days. My husband and I like to split a mini coffee cake in the mornings with some hot tea or have it in the late afternoon as a snack. This recipe can also be found at gardengirlrecipes.com.. .. Ingredients. STREUSEL:½ cup light brown sugar. ½ cup rolled oats. ⅓ cup all purpose flour. ¼ teaspoon salt. 6 tablespoons cold unsalted butter, cut into small pieces. COFFEE CAKE:2 cups fresh blueberries. 2 cups + 2 tbsp all purpose flour. 1 tablespoon baking powder. 1 teaspoon ground cinnamon. ½ teaspoon salt¼ teaspoon ground nutmeg. 2/3 cup whole milk, at room temperature. 1 teaspoon vanilla extract. 8 tablespoons unsalted butter, at room temperature plus more for coating. ½ cup + 2 tbsp packed light brown sugar. ½ cup + 2 tbsp granulated sugar. 2 large eggs, at room temperature. Teachers! Did you use this instructable in your classroom? Add a Teacher Note to share how you incorporated it into your lesson.. Preheat the oven to 350°F. Then combine all the dry ingredients for the streusel.. Add the butter and place in the fridge until ready to use.. Combine 2 cups of flour with the baking powder, salt, cinnamon, and nutmeg.. Coat the blueberries in 2 tablespoons of flour.. Combine the milk and the vanilla extract.. In the bowl of a stand mixer fitted with a paddle attachment, combine the sugars and the butter.. Add the eggs one at a time.. Add a third of the flour mixture and mix until just combined. Then add a third of the milk mixture and mix until just incorporated. Repeat until all the flour and milk have been thoroughly combined. (Do not overmix or the cake will be tough).. Fold in the blueberries leaving the excess flour.. Coat a 10-inch springform pan with butter. Then line the bottom with parchment paper and coat the parchment with butter.. Fill the springform pan with the batter.. Remove the streusel from the fridge and sprinkle it on top of the batter.. Bake until the top is golden brown, about 55 to 60 minutes.. Remove the pan from the oven and let it cool on a wire rack for at least 20 minutes.. Participated in the Baking Challenge. Did you make this project? Share it with us!. 8,500 Enrolled. 1 year ago. Mmm looks delish :).Reply1 year ago . It was delicious! :). Question1 year agoon Step 1. Frozen blueberries?. Answer1 year ago . I used fresh to make this dish, but frozen blueberries should work too.. © 2020 Autodesk, Inc.. ']})
xx = tfidf.fit_transform(connew).toarray()
#xx = TfidfVectorizer(encoding='utf-8',max_df=10,min_df=1,max_features=300).fit_transform(connew).toarray()
print(xx)



[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.0637631  0.09219479 0.10280809 ... 0.         0.         0.        ]
 [0.07240623 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [261]:
DTC_pred1 = DTC.predict(xx)
len(connew)

75

In [262]:
DTC_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [263]:
DTC_pred

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,

In [264]:
################################# NAIVE BAYES ##############################################

In [265]:
Naive = naive_bayes.MultinomialNB()
Naive.fit(features_train, y_train)
Naive_pred = Naive.predict(features_test)


In [266]:
print("Naive Bayes Training Accuracy Score -> ",accuracy_score(y_train, Naive.predict(features_train))*100)
print("Naive Bayes Test Accuracy Score -> ",accuracy_score(y_test, Naive.predict(features_test))*100)

Naive Bayes Training Accuracy Score ->  99.87107864202837
Naive Bayes Test Accuracy Score ->  99.27007299270073


In [267]:
matrix = confusion_matrix(y_test, Naive_pred)
print("confusion matrix")
print(matrix)
report = classification_report(y_test, Naive_pred)
print(report)
from sklearn.metrics import confusion_matrix


confusion matrix
[[201   1]
 [  2 207]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       202
           1       1.00      0.99      0.99       209

    accuracy                           0.99       411
   macro avg       0.99      0.99      0.99       411
weighted avg       0.99      0.99      0.99       411



In [268]:
#code for checking the prediction
Naive_pred1 = Naive.predict(xx)
Naive_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [269]:

######################################## SVM ##############################################

In [270]:
#SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='scale', coef0=0.1, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
SVM = svm.LinearSVC(C=0.1)
SVM.fit(features_train, y_train)
SVM_pred = SVM.predict(features_test)


In [271]:
print("svm Training Accuracy Score -> ",accuracy_score(y_train, SVM.predict(features_train))*100)
print("svmtest Accuracy Score -> ",accuracy_score(y_test, SVM.predict(features_test))*100)


svm Training Accuracy Score ->  100.0
svmtest Accuracy Score ->  99.7566909975669


In [272]:
matrix = confusion_matrix(y_test, SVM_pred)
print("confusion matrix")
print(matrix)
report = classification_report(y_test, SVM_pred) 
print(report)
from sklearn.metrics import confusion_matrix


confusion matrix
[[201   1]
 [  0 209]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       202
           1       1.00      1.00      1.00       209

    accuracy                           1.00       411
   macro avg       1.00      1.00      1.00       411
weighted avg       1.00      1.00      1.00       411



In [273]:
#code for checking the prediction
SVM_pred1 = SVM.predict(xx)
SVM_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [274]:
######################################## KNN ##############################################

In [275]:
#knn = KNeighborsClassifier(n_neighbors=75, weights='distance', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
knn = KNeighborsClassifier(n_neighbors=7,weights='distance')
knn.fit(features_train, y_train)
knn_pred = knn.predict(features_test)
#y_score = SVM.decision_function(features_test)

In [276]:
print("knn Accuracy Score -> ",accuracy_score(labels_train, knn.predict(features_train))*100)
print("knn Accuracy Score -> ",accuracy_score(y_test, knn.predict(features_test))*100)


knn Accuracy Score ->  100.0
knn Accuracy Score ->  98.29683698296837


In [277]:
matrix = confusion_matrix(y_test, knn_pred)
print("confusion matrix")
print(matrix)
report = classification_report(y_test, knn_pred)
print(report)
from sklearn.metrics import confusion_matrix


confusion matrix
[[200   2]
 [  5 204]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       202
           1       0.99      0.98      0.98       209

    accuracy                           0.98       411
   macro avg       0.98      0.98      0.98       411
weighted avg       0.98      0.98      0.98       411



In [278]:
#code for checking the prediction
knn_pred1 = knn.predict(xx)
knn_pred1

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [279]:
############################################# SGD #######################################

In [280]:
#clf = SGDClassifier(loss="log", penalty="l1", max_iter=100)
SGD = SGDClassifier(random_state=8)
SGD.fit(features_train, y_train)
SGD_pred = SGD.predict(features_test)

In [281]:
print("SGD Training Accuracy Score  ->",accuracy_score(y_train, SGD.predict(features_train))*100)
print("SGD Testing Accuracy Score  ->",accuracy_score(y_test, SGD.predict(features_test))*100)

SGD Training Accuracy Score  -> 100.0
SGD Testing Accuracy Score  -> 99.27007299270073


In [282]:
matrix = confusion_matrix(y_test, SGD_pred)
print("confusion matrix")
print(matrix)
report = classification_report(y_test, SGD_pred)
print(report)
from sklearn.metrics import confusion_matrix


confusion matrix
[[202   0]
 [  3 206]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       202
           1       1.00      0.99      0.99       209

    accuracy                           0.99       411
   macro avg       0.99      0.99      0.99       411
weighted avg       0.99      0.99      0.99       411



In [288]:
#code for checking the prediction
SGD_pred1 = clf.predict(xx)
SGD_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [284]:
############################################# Random Forest ########################################

In [285]:
 
random = RandomForestClassifier(n_estimators=10,max_features='log2',random_state=8)
#regressor = RandomForestRegressor(n_estimators=2, max_depth=None,min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None,bootstrap=True, oob_score=False, n_jobs=1, random_state=None, verbose=0, warm_start=False)

random.fit(features_train, y_train)
random_pred = random.predict(features_test)


In [286]:
print("Random Forest Training Accuracy Score  ->",accuracy_score(y_train, random.predict(features_train))*100)
print("Random Forest Test Accuracy Score  ->",accuracy_score(y_test, random.predict(features_test))*100)

Random Forest Training Accuracy Score  -> 100.0
Random Forest Test Accuracy Score  -> 100.0


In [213]:
matrix = confusion_matrix(y_test, random_pred)
print("confusion matrix")
print(matrix)
report = classification_report(y_test, random_pred)
print(report)
from sklearn.metrics import confusion_matrix


confusion matrix
[[202   0]
 [  0 209]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       202
           1       1.00      1.00      1.00       209

    accuracy                           1.00       411
   macro avg       1.00      1.00      1.00       411
weighted avg       1.00      1.00      1.00       411



In [214]:
random_pred

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,

In [215]:
#code for checking the prediction
random_pred1 = random.predict(xx)
random_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)